### ISSUE TITLE
Div width excesses full screen size in Top Categories and Featured Topics 

### ISSUE THREAD

**Issue by Lada496** [Lada496/clone-udemy#9]
**related code snippets**
https://github.com/Lada496/clone-udemy/blob/3999310be02e6318b578757fa298c9d0336766a9/src/container/TopCategoriesContainer.jsx#L32-L36

https://github.com/Lada496/clone-udemy/blob/3999310be02e6318b578757fa298c9d0336766a9/src/container/FeaturedTopicsContainer.jsx#L35-L39

**Screen shots**
<img width="918" alt="Screen Shot 2022-02-22 at 15 19 49" src="https://user-images.githubusercontent.com/67321065/155248234-c071b389-7655-4ffe-aa66-ba04fabb3497.png">

<img width="924" alt="Screen Shot 2022-02-22 at 15 19 31" src="https://user-images.githubusercontent.com/67321065/155248229-9dc615a7-9498-4649-a03e-ed515164169c.png">

**condition**
screen width is smaller than 134rem

**suggestion**
use grid instead of flex

@Ayako-Yokoe

**Comment by Ayako-Yokoe** [comment]
```
const TopCategoriesSection = styled.section`
  width: 100%;
  max-width: 134rem;
  margin-right: auto;
  margin-left: auto;
  padding: 0 2.4rem;
`
```

If I omit  **width: 100%;** for both TopCategories and FeaturedTopics, it works just fine. Should I still refactor it?

@Lada496

**Comment by Lada496** [comment]
@Ayako-Yokoe Thanks for your suggestion. You don't need to use grid because all I want is that no elements exceed 100% of window size at any size of windows.

**Comment by Ayako-Yokoe** [comment]
Thank you.
I just sent a pull request, so I'd like you to check it. Thanks.
